hintList:
  easy:
    - "エメラルドを集めて、製図家と地図を交換しよう！"
    - "scorerankingコマンドで、スコア情報を確認しよう！"
    - "scorelistコマンドを使うと、過去のスコア情報も確認できるよ！"
  normal:
    - "エメラルドを集めて、製図家と地図を交換しよう！"
    - "ゲーム開始位置から半径20ブロックに落ちているがくぶちを探してみよう！"
    - "scorerankingコマンドで、スコア情報を確認しよう！"
    - "scorelistコマンドを使うと、過去のスコア情報も確認できるよ！"
  hard:
    - "エメラルドを集めて、製図家と地図を交換しよう！"
    - "ゲーム開始位置から半径20ブロックに落ちているがくぶちを探してみよう！"
    - "ゲーム開始位置から半径30ブロックに落ちている望遠鏡を探してみよう！"
    - "scorerankingコマンドで、スコア情報を確認しよう！"
    - "scorelistコマンドを使うと、過去のスコア情報も確認できるよ！"
